// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package dto

import (
	"github.com/gogf/gf/v2/frame/g"
)

// AdminRoleDept is the golang structure of table hg_admin_role_dept for DAO operations like Where/Data.
type AdminRoleDept struct {
	g.Meta `orm:"table:hg_admin_role_dept, dto:true"`
	RoleId interface{} // 角色ID
	DeptId interface{} // 部门ID
}
