// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package dto

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// SysConfig is the golang structure of table hg_sys_config for DAO operations like Where/Data.
type SysConfig struct {
	g.Meta    `orm:"table:hg_sys_config, dto:true"`
	Id        interface{} // 配置ID
	Name      interface{} // 参数名称
	Key       interface{} // 参数键名
	Value     interface{} // 参数键值
	IsDefault interface{} // 是否默认
	Status    interface{} // 状态
	Remark    interface{} // 备注
	CreatedAt *gtime.Time // 创建时间
	UpdatedAt *gtime.Time // 更新时间
}
