// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package dto

import (
	"github.com/gogf/gf/v2/frame/g"
)

// SysProvinces is the golang structure of table hg_sys_provinces for DAO operations like Where/Data.
type SysProvinces struct {
	g.Meta     `orm:"table:hg_sys_provinces, dto:true"`
	Id         interface{} // ID
	Title      interface{} // 栏目名
	Pid        interface{} // 父栏目
	ShortTitle interface{} // 缩写
	Areacode   interface{} // 区域编码
	Zipcode    interface{} // 邮政编码
	Pinyin     interface{} // 拼音
	Lng        interface{} // 经度
	Lat        interface{} // 纬度
	Level      interface{} // 级别
	Tree       interface{} //
	Sort       interface{} // 排序
}
