import { renderIcon } from '@/utils/index';
import {
  AppstoreOutlined,
  CheckCircleOutlined,
  DashboardOutlined,
  ExclamationCircleOutlined,
  ProfileOutlined,
  ProjectOutlined,
  SettingOutlined,
  TableOutlined,
  WalletOutlined,
  DeleteOutlined,
  EditOutlined,
} from '@vicons/antd';
import {
  DesktopOutline,
  DocumentTextOutline,
  OptionsSharp,
  SettingsOutline,
  LogoBuffer,
  KeyOutline,
  VolumeLowOutline,
  CodeSlashOutline,
  EaselOutline,
  TimerOutline,
  OptionsOutline,
} from '@vicons/ionicons5';

//前端路由图标映射表
export const constantRouterIcon = {
  EditOutlined: renderIcon(EditOutlined),
  DeleteOutlined: renderIcon(DeleteOutlined),
  OptionsOutline: renderIcon(OptionsOutline),
  TimerOutline: renderIcon(TimerOutline),
  EaselOutline: renderIcon(EaselOutline),
  CodeSlashOutline: renderIcon(CodeSlashOutline),
  VolumeLowOutline: renderIcon(VolumeLowOutline),
  DashboardOutlined: renderIcon(DashboardOutlined),
  SettingsOutline: renderIcon(SettingsOutline),
  OptionsSharp: renderIcon(OptionsSharp),
  TableOutlined: renderIcon(TableOutlined),
  ExclamationCircleOutlined: renderIcon(ExclamationCircleOutlined),
  ProfileOutlined: renderIcon(ProfileOutlined),
  CheckCircleOutlined: renderIcon(CheckCircleOutlined),
  SettingOutlined: renderIcon(SettingOutlined),
  WalletOutlined: renderIcon(WalletOutlined),
  DesktopOutline: renderIcon(DesktopOutline),
  DocumentTextOutline: renderIcon(DocumentTextOutline),
  ProjectOutlined: renderIcon(ProjectOutlined),
  AppstoreOutlined: renderIcon(AppstoreOutlined),
  LogoBuffer: renderIcon(LogoBuffer),
  KeyOutline: renderIcon(KeyOutline),
};
