// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// AdminRole is the golang structure of table hg_admin_role for DAO operations like Where/Data.
type AdminRole struct {
	g.Meta            `orm:"table:hg_admin_role, do:true"`
	Id                interface{} // 角色ID
	Name              interface{} // 角色名称
	Key               interface{} // 角色权限字符串
	DataScope         interface{} // 数据范围（1：全部数据权限 2：自定数据权限 3：本部门数据权限 4：本部门及以下数据权限）
	MenuCheckStrictly interface{} // 菜单树选择项是否关联显示
	DeptCheckStrictly interface{} // 部门树选择项是否关联显示
	Remark            interface{} // 备注
	Sort              interface{} // 排序
	Status            interface{} // 角色状态
	CreatedAt         *gtime.Time // 创建时间
	UpdatedAt         *gtime.Time // 更新时间
}
