// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// AdminNotice is the golang structure of table hg_admin_notice for DAO operations like Where/Data.
type AdminNotice struct {
	g.Meta    `orm:"table:hg_admin_notice, do:true"`
	Id        interface{} // 公告ID
	Title     interface{} // 公告标题
	Type      interface{} // 公告类型
	Content   interface{} // 公告内容
	Receiver  interface{} // 接收者
	Reader    interface{} // 已读人
	Remark    interface{} // 备注
	Sort      interface{} // 排序
	Status    interface{} // 公告状态
	CreatedAt *gtime.Time // 创建时间
	UpdatedAt *gtime.Time // 更新时间
}
