// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// AdminMember is the golang structure of table hg_admin_member for DAO operations like Where/Data.
type AdminMember struct {
	g.Meta             `orm:"table:hg_admin_member, do:true"`
	Id                 interface{} // 管理员ID
	DeptId             interface{} // 部门ID
	RoleId             interface{} // 角色ID
	RealName           interface{} // 真实姓名
	Username           interface{} // 帐号
	PasswordHash       interface{} // 密码
	Salt               interface{} // 密码盐
	AuthKey            interface{} // 授权令牌
	PasswordResetToken interface{} // 密码重置令牌
	Avatar             interface{} // 头像
	Sex                interface{} // 性别
	Qq                 interface{} // qq
	Email              interface{} // 邮箱
	Mobile             interface{} // 手机号码
	Birthday           *gtime.Time // 生日
	ProvinceId         interface{} // 省编码
	CityId             interface{} // 城市编码
	CountyId           interface{} // 区域编码
	Address            interface{} // 联系地址
	VisitCount         interface{} // 访问次数
	LastTime           interface{} // 最后一次登录时间
	LastIp             interface{} // 最后一次登录ip
	Pid                interface{} // 上级管理员ID
	Level              interface{} // 关系树等级
	Tree               interface{} // 关系树
	Remark             interface{} // 备注
	Status             interface{} // 状态
	CreatedAt          *gtime.Time // 创建时间
	UpdatedAt          *gtime.Time // 修改时间
}
