// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// SysLog is the golang structure of table hg_sys_log for DAO operations like Where/Data.
type SysLog struct {
	g.Meta     `orm:"table:hg_sys_log, do:true"`
	Id         interface{} //
	AppId      interface{} // 应用id
	MerchantId interface{} // 商户id
	MemberId   interface{} // 用户id
	Method     interface{} // 提交类型
	Module     interface{} // 模块
	Url        interface{} // 提交url
	GetData    interface{} // get数据
	PostData   interface{} // post数据
	HeaderData interface{} // header数据
	Ip         interface{} // ip地址
	ProvinceId interface{} // 省编码
	CityId     interface{} // 市编码
	ErrorCode  interface{} // 报错code
	ErrorMsg   interface{} // 报错信息
	ErrorData  interface{} // 报错日志
	ReqId      interface{} // 对外id
	Timestamp  interface{} // 响应时间
	UserAgent  interface{} // UA信息
	TakeUpTime interface{} // 请求耗时
	Status     interface{} // 状态
	CreatedAt  *gtime.Time // 创建时间
	UpdatedAt  *gtime.Time // 修改时间
}
