// ================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// You can delete these comments if you wish manually maintain this interface file.
// ================================================================================

package service

import (
	"context"
	"hotgo/addons/flashbanner/model"
	"hotgo/addons/flashbanner/model/input/sysin"
)

type (
	ISysConfig interface {
		GetBasic(ctx context.Context) (conf *model.BasicConfig, err error)
		GetConfigByGroup(ctx context.Context, in *sysin.GetConfigInp) (res *sysin.GetConfigModel, err error)
		UpdateConfigByGroup(ctx context.Context, in *sysin.UpdateConfigInp) error
	}
	ISysIndex interface {
		Test(ctx context.Context, in *sysin.IndexTestInp) (res *sysin.IndexTestModel, err error)
	}
	ISysBanner interface {
		Create(ctx context.Context, in *sysin.BannerCreateInp) (err error)
		Edit(ctx context.Context, in *sysin.BannerEditInp) (err error)
		Delete(ctx context.Context, in *sysin.BannerDeleteInp) (err error)
		View(ctx context.Context, in *sysin.BannerViewInp) (res *sysin.BannerViewModel, err error)
		List(ctx context.Context, in *sysin.BannerListInp) (list []*sysin.BannerListModel, totalCount int, err error)
		Status(ctx context.Context, in *sysin.BannerStatusInp) (err error)
		GetMaxSort(ctx context.Context) (maxSort int, err error)
	}
)

var (
	localSysConfig ISysConfig
	localSysIndex  ISysIndex
	localSysBanner ISysBanner
)

func SysConfig() ISysConfig {
	if localSysConfig == nil {
		panic("implement not found for interface ISysConfig, forgot register?")
	}
	return localSysConfig
}

func RegisterSysConfig(i ISysConfig) {
	localSysConfig = i
}

func SysIndex() ISysIndex {
	if localSysIndex == nil {
		panic("implement not found for interface ISysIndex, forgot register?")
	}
	return localSysIndex
}

func RegisterSysIndex(i ISysIndex) {
	localSysIndex = i
}

func SysBanner() ISysBanner {
	if localSysBanner == nil {
		panic("implement not found for interface ISysBanner, forgot register?")
	}
	return localSysBanner
}

func RegisterSysBanner(i ISysBanner) {
	localSysBanner = i
}
