// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package member

import (
	"hotgo/api/api/member"
)

type ControllerV1 struct{}

func NewV1() member.IMemberV1 {
	return &ControllerV1{}
}
