// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

// AdminRoleMenu is the golang structure for table admin_role_menu.
type AdminRoleMenu struct {
	RoleId int64 `json:"role_id" description:"角色ID"`
	MenuId int64 `json:"menu_id" description:"菜单ID"`
}
