// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// AdminMember is the golang structure for table admin_member.
type AdminMember struct {
	Id                 int64       `json:"id"                   description:""`
	DeptId             int64       `json:"dept_id"              description:"部门ID"`
	Username           string      `json:"username"             description:"帐号"`
	PasswordHash       string      `json:"password_hash"        description:"密码"`
	Salt               string      `json:"salt"                 description:"密码盐"`
	AuthKey            string      `json:"auth_key"             description:"授权令牌"`
	PasswordResetToken string      `json:"password_reset_token" description:"密码重置令牌"`
	Type               string      `json:"type"                 description:"1:普通管理员;10超级管理员"`
	Realname           string      `json:"realname"             description:"真实姓名"`
	Avatar             string      `json:"avatar"               description:"头像"`
	Sex                string      `json:"sex"                  description:"性别[0:未知;1:男;2:女]"`
	Qq                 string      `json:"qq"                   description:"qq"`
	Email              string      `json:"email"                description:"邮箱"`
	Birthday           *gtime.Time `json:"birthday"             description:"生日"`
	ProvinceId         int         `json:"province_id"          description:"省"`
	CityId             int         `json:"city_id"              description:"城市"`
	AreaId             int         `json:"area_id"              description:"地区"`
	Address            string      `json:"address"              description:"默认地址"`
	Mobile             string      `json:"mobile"               description:"手机号码"`
	HomePhone          string      `json:"home_phone"           description:"家庭号码"`
	DingtalkRobotToken string      `json:"dingtalk_robot_token" description:"钉钉机器人token"`
	VisitCount         uint        `json:"visit_count"          description:"访问次数"`
	LastTime           int         `json:"last_time"            description:"最后一次登录时间"`
	LastIp             string      `json:"last_ip"              description:"最后一次登录ip"`
	Role               int64       `json:"role"                 description:"权限"`
	Remark             string      `json:"remark"               description:"备注"`
	Status             string      `json:"status"               description:"状态"`
	CreatedAt          *gtime.Time `json:"created_at"           description:"创建时间"`
	UpdatedAt          *gtime.Time `json:"updated_at"           description:"修改时间"`
}
