// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// AdminMenu is the golang structure for table admin_menu.
type AdminMenu struct {
	Id        int64       `json:"id"         description:"菜单ID"`
	Pid       int64       `json:"pid"        description:"父菜单ID"`
	Name      string      `json:"name"       description:"菜单名称"`
	Code      string      `json:"code"       description:"菜单编码"`
	Icon      string      `json:"icon"       description:"菜单图标"`
	Type      string      `json:"type"       description:"菜单类型（M目录 C菜单 F按钮）"`
	Perms     string      `json:"perms"      description:"权限标识"`
	Path      string      `json:"path"       description:"路由地址"`
	Component string      `json:"component"  description:"组件路径"`
	Query     string      `json:"query"      description:"路由参数"`
	IsFrame   string      `json:"is_frame"   description:"是否内嵌"`
	IsCache   string      `json:"is_cache"   description:"是否不缓存"`
	IsVisible string      `json:"is_visible" description:"是否隐藏"`
	Remark    string      `json:"remark"     description:"备注"`
	Level     int         `json:"level"      description:"级别"`
	Tree      string      `json:"tree"       description:"树"`
	Sort      int         `json:"sort"       description:"排序"`
	Status    string      `json:"status"     description:"菜单状态"`
	CreatedAt *gtime.Time `json:"created_at" description:"创建时间"`
	UpdatedAt *gtime.Time `json:"updated_at" description:"更新时间"`
}
