// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// AdminRole is the golang structure for table admin_role.
type AdminRole struct {
	Id                int64       `json:"id"                  description:"角色ID"`
	Name              string      `json:"name"                description:"角色名称"`
	Key               string      `json:"key"                 description:"角色权限字符串"`
	DataScope         int         `json:"data_scope"          description:"数据范围（1：全部数据权限 2：自定数据权限 3：本部门数据权限 4：本部门及以下数据权限）"`
	MenuCheckStrictly int         `json:"menu_check_strictly" description:"菜单树选择项是否关联显示"`
	DeptCheckStrictly int         `json:"dept_check_strictly" description:"部门树选择项是否关联显示"`
	Remark            string      `json:"remark"              description:"备注"`
	Sort              int         `json:"sort"                description:"排序"`
	Status            string      `json:"status"              description:"角色状态"`
	CreatedAt         *gtime.Time `json:"created_at"          description:"创建时间"`
	UpdatedAt         *gtime.Time `json:"updated_at"          description:"更新时间"`
}
