// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

// AdminMemberRole is the golang structure for table admin_member_role.
type AdminMemberRole struct {
	MemberId int64 `json:"member_id" description:"用户ID"`
	RoleId   int64 `json:"role_id"   description:"角色ID"`
}
