// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// AdminMenuOld is the golang structure for table admin_menu_old.
type AdminMenuOld struct {
	Id        int64       `json:"id"         description:"菜单ID"`
	Pid       int64       `json:"pid"        description:"父菜单ID"`
	Name      string      `json:"name"       description:"菜单名称"`
	Icon      string      `json:"icon"       description:"菜单图标"`
	Type      string      `json:"type"       description:"菜单类型（M目录 C菜单 F按钮）"`
	Perms     string      `json:"perms"      description:"权限标识"`
	Path      string      `json:"path"       description:"路由地址"`
	Component string      `json:"component"  description:"组件路径"`
	Query     string      `json:"query"      description:"路由参数"`
	IsFrame   int         `json:"is_frame"   description:"是否为外链（0是 1否）"`
	IsCache   int         `json:"is_cache"   description:"是否缓存（0缓存 1不缓存）"`
	IsVisible int         `json:"is_visible" description:"菜单状态（0显示 1隐藏）"`
	Remark    string      `json:"remark"     description:"备注"`
	Level     int         `json:"level"      description:"级别"`
	Tree      string      `json:"tree"       description:"树"`
	Sort      int         `json:"sort"       description:"排序"`
	Status    int         `json:"status"     description:"菜单状态"`
	CreatedAt *gtime.Time `json:"created_at" description:"创建时间"`
	UpdatedAt *gtime.Time `json:"updated_at" description:"更新时间"`
}
