// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

// AdminMemberPost is the golang structure for table admin_member_post.
type AdminMemberPost struct {
	MemberId int64 `json:"member_id" description:"用户ID"`
	PostId   int64 `json:"post_id"   description:"岗位ID"`
}
