// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// SysLog is the golang structure for table sys_log.
type SysLog struct {
	Id         int64       `json:"id"           description:""`
	AppId      string      `json:"app_id"       description:"应用id"`
	MerchantId uint        `json:"merchant_id"  description:"商户id"`
	MemberId   int         `json:"member_id"    description:"用户id"`
	Method     string      `json:"method"       description:"提交类型"`
	Module     string      `json:"module"       description:"模块"`
	Url        string      `json:"url"          description:"提交url"`
	GetData    string      `json:"get_data"     description:"get数据"`
	PostData   string      `json:"post_data"    description:"post数据"`
	HeaderData string      `json:"header_data"  description:"header数据"`
	Ip         string      `json:"ip"           description:"ip地址"`
	ProvinceId int         `json:"province_id"  description:"省编码"`
	CityId     int         `json:"city_id"      description:"市编码"`
	ErrorCode  int         `json:"error_code"   description:"报错code"`
	ErrorMsg   string      `json:"error_msg"    description:"报错信息"`
	ErrorData  string      `json:"error_data"   description:"报错日志"`
	ReqId      string      `json:"req_id"       description:"对外id"`
	Timestamp  int         `json:"timestamp"    description:"响应时间"`
	UserAgent  string      `json:"user_agent"   description:"UA信息"`
	TakeUpTime int64       `json:"take_up_time" description:"请求耗时"`
	Status     string      `json:"status"       description:"状态"`
	CreatedAt  *gtime.Time `json:"created_at"   description:"创建时间"`
	UpdatedAt  *gtime.Time `json:"updated_at"   description:"修改时间"`
}
