// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// SysDictType is the golang structure for table sys_dict_type.
type SysDictType struct {
	Id        int64       `json:"id"         description:"字典主键"`
	Name      string      `json:"name"       description:"字典名称"`
	Type      string      `json:"type"       description:"字典类型"`
	Sort      int         `json:"sort"       description:"排序"`
	Remark    string      `json:"remark"     description:"备注"`
	Status    string      `json:"status"     description:"状态"`
	CreatedAt *gtime.Time `json:"created_at" description:"创建时间"`
	UpdatedAt *gtime.Time `json:"updated_at" description:"更新时间"`
}
