// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

// SysProvinces is the golang structure for table sys_provinces.
type SysProvinces struct {
	Id         int    `json:"id"          description:"ID"`
	Title      string `json:"title"       description:"栏目名"`
	Pid        int    `json:"pid"         description:"父栏目"`
	ShortTitle string `json:"short_title" description:"缩写"`
	Areacode   int    `json:"areacode"    description:"区域编码"`
	Zipcode    int    `json:"zipcode"     description:"邮政编码"`
	Pinyin     string `json:"pinyin"      description:"拼音"`
	Lng        string `json:"lng"         description:"经度"`
	Lat        string `json:"lat"         description:"纬度"`
	Level      int    `json:"level"       description:"级别"`
	Tree       string `json:"tree"        description:""`
	Sort       uint   `json:"sort"        description:"排序"`
}
