// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// SysDictData is the golang structure for table sys_dict_data.
type SysDictData struct {
	Id        int64       `json:"id"         description:"字典编码"`
	Label     string      `json:"label"      description:"字典标签"`
	Value     string      `json:"value"      description:"字典键值"`
	Type      string      `json:"type"       description:"字典类型"`
	ListClass string      `json:"list_class" description:"表格回显样式"`
	IsDefault string      `json:"is_default" description:"是否默认"`
	Sort      int         `json:"sort"       description:"字典排序"`
	Remark    string      `json:"remark"     description:"备注"`
	Status    string      `json:"status"     description:"状态"`
	CreatedAt *gtime.Time `json:"created_at" description:"创建时间"`
	UpdatedAt *gtime.Time `json:"updated_at" description:"更新时间"`
}
