// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package logic

import (
	_ "hotgo/internal/logic/admin"
	_ "hotgo/internal/logic/common"
	_ "hotgo/internal/logic/hook"
	_ "hotgo/internal/logic/middleware"
	_ "hotgo/internal/logic/sys"
	_ "hotgo/internal/logic/tcpclient"
	_ "hotgo/internal/logic/tcpserver"
	_ "hotgo/internal/logic/view"
)
