// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"hotgo/internal/dao/internal"
)

// internalAdminRoleDeptDao is internal type for wrapping internal DAO implements.
type internalAdminRoleDeptDao = *internal.AdminRoleDeptDao

// adminRoleDeptDao is the data access object for table hg_admin_role_dept.
// You can define custom methods on it to extend its functionality as you wish.
type adminRoleDeptDao struct {
	internalAdminRoleDeptDao
}

var (
	// AdminRoleDept is globally common accessible object for table hg_admin_role_dept operations.
	AdminRoleDept = adminRoleDeptDao{
		internal.NewAdminRoleDeptDao(),
	}
)

// Fill with you ideas below.
