// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"hotgo/internal/dao/internal"
)

// internalDemoDao is internal type for wrapping internal DAO implements.
type internalDemoDao = *internal.DemoDao

// demoDao is the data access object for table hg_demo.
// You can define custom methods on it to extend its functionality as you wish.
type demoDao struct {
	internalDemoDao
}

var (
	// Demo is globally public accessible object for table hg_demo operations.
	Demo = demoDao{
		internal.NewDemoDao(),
	}
)

// Fill with you ideas below.
