// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"hotgo/internal/dao/internal"
)

// sysGenCodesDao is the data access object for the table hg_sys_gen_codes.
// You can define custom methods on it to extend its functionality as needed.
type sysGenCodesDao struct {
	*internal.SysGenCodesDao
}

var (
	// SysGenCodes is a globally accessible object for table hg_sys_gen_codes operations.
	SysGenCodes = sysGenCodesDao{internal.NewSysGenCodesDao()}
)

// Add your custom methods and functionality below.
