// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"hotgo/internal/dao/internal"
)

// sysGenCurdDemoDao is the data access object for the table hg_sys_gen_curd_demo.
// You can define custom methods on it to extend its functionality as needed.
type sysGenCurdDemoDao struct {
	*internal.SysGenCurdDemoDao
}

var (
	// SysGenCurdDemo is a globally accessible object for table hg_sys_gen_curd_demo operations.
	SysGenCurdDemo = sysGenCurdDemoDao{internal.NewSysGenCurdDemoDao()}
)

// Add your custom methods and functionality below.
