// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package pay

import (
	"hotgo/api/api/pay"
)

type ControllerV1 struct{}

func NewV1() pay.IPayV1 {
	return &ControllerV1{}
}
