// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

//
// @Package  dao
// @Description 
// @Author  Ms <133814250@qq.com>
//
package dao

import (
	"github.com/bufanyun/hotgo/app/service/internal/dao/internal"
)

// adminRoleDeptDao is the data access object for table hg_admin_role_dept.
// You can define custom methods on it to extend its functionality as you wish.
type adminRoleDeptDao struct {
	*internal.AdminRoleDeptDao
}

var (
	// AdminRoleDept is globally public accessible object for table hg_admin_role_dept operations.
	AdminRoleDept = adminRoleDeptDao{
		internal.NewAdminRoleDeptDao(),
	}
)

// Fill with you ideas below.
