// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// AdminMember is the golang structure for table admin_member.
type AdminMember struct {
	Id                 int64       `json:"id"                 description:"管理员ID"`
	DeptId             int64       `json:"deptId"             description:"部门ID"`
	RoleId             int64       `json:"roleId"             description:"角色ID"`
	RealName           string      `json:"realName"           description:"真实姓名"`
	Username           string      `json:"username"           description:"帐号"`
	PasswordHash       string      `json:"passwordHash"       description:"密码"`
	Salt               string      `json:"salt"               description:"密码盐"`
	AuthKey            string      `json:"authKey"            description:"授权令牌"`
	PasswordResetToken string      `json:"passwordResetToken" description:"密码重置令牌"`
	Avatar             string      `json:"avatar"             description:"头像"`
	Sex                int         `json:"sex"                description:"性别"`
	Qq                 string      `json:"qq"                 description:"qq"`
	Email              string      `json:"email"              description:"邮箱"`
	Mobile             string      `json:"mobile"             description:"手机号码"`
	Birthday           *gtime.Time `json:"birthday"           description:"生日"`
	ProvinceId         int64       `json:"provinceId"         description:"省编码"`
	CityId             int64       `json:"cityId"             description:"城市编码"`
	CountyId           int64       `json:"countyId"           description:"区域编码"`
	Address            string      `json:"address"            description:"联系地址"`
	VisitCount         uint        `json:"visitCount"         description:"访问次数"`
	LastTime           int         `json:"lastTime"           description:"最后一次登录时间"`
	LastIp             string      `json:"lastIp"             description:"最后一次登录ip"`
	Pid                int64       `json:"pid"                description:"上级管理员ID"`
	Level              int         `json:"level"              description:"关系树等级"`
	Tree               string      `json:"tree"               description:"关系树"`
	Remark             string      `json:"remark"             description:"备注"`
	Status             int         `json:"status"             description:"状态"`
	CreatedAt          *gtime.Time `json:"createdAt"          description:"创建时间"`
	UpdatedAt          *gtime.Time `json:"updatedAt"          description:"修改时间"`
}
