// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

// AdminMemberRole is the golang structure for table admin_member_role.
type AdminMemberRole struct {
	MemberId int64 `json:"memberId" description:"用户ID"`
	RoleId   int64 `json:"roleId"   description:"角色ID"`
}
