// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// AdminMember is the golang structure for table admin_member.
type AdminMember struct {
	Id                 int64       `json:"id"                 description:""`
	DeptId             int64       `json:"deptId"             description:"部门ID"`
	Username           string      `json:"username"           description:"帐号"`
	PasswordHash       string      `json:"passwordHash"       description:"密码"`
	Salt               string      `json:"salt"               description:"密码盐"`
	AuthKey            string      `json:"authKey"            description:"授权令牌"`
	PasswordResetToken string      `json:"passwordResetToken" description:"密码重置令牌"`
	Type               string      `json:"type"               description:"1:普通管理员;10超级管理员"`
	Realname           string      `json:"realname"           description:"真实姓名"`
	Avatar             string      `json:"avatar"             description:"头像"`
	Sex                int         `json:"sex"                description:"性别[1:男;2:女;3:未知]"`
	Qq                 string      `json:"qq"                 description:"qq"`
	Email              string      `json:"email"              description:"邮箱"`
	Birthday           *gtime.Time `json:"birthday"           description:"生日"`
	ProvinceId         int         `json:"provinceId"         description:"省"`
	CityId             int         `json:"cityId"             description:"城市"`
	AreaId             int         `json:"areaId"             description:"地区"`
	Address            string      `json:"address"            description:"默认地址"`
	Mobile             string      `json:"mobile"             description:"手机号码"`
	HomePhone          string      `json:"homePhone"          description:"家庭号码"`
	DingtalkRobotToken string      `json:"dingtalkRobotToken" description:"钉钉机器人token"`
	VisitCount         uint        `json:"visitCount"         description:"访问次数"`
	LastTime           int         `json:"lastTime"           description:"最后一次登录时间"`
	LastIp             string      `json:"lastIp"             description:"最后一次登录ip"`
	Role               int64       `json:"role"               description:"权限"`
	Remark             string      `json:"remark"             description:"备注"`
	Status             int         `json:"status"             description:"状态"`
	CreatedAt          *gtime.Time `json:"createdAt"          description:"创建时间"`
	UpdatedAt          *gtime.Time `json:"updatedAt"          description:"修改时间"`
}
