// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

// AdminRoleMenu is the golang structure for table admin_role_menu.
type AdminRoleMenu struct {
	RoleId int64 `json:"roleId" description:"角色ID"`
	MenuId int64 `json:"menuId" description:"菜单ID"`
}
