// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

// AdminRoleDept is the golang structure for table admin_role_dept.
type AdminRoleDept struct {
	RoleId int64 `json:"roleId" description:"角色ID"`
	DeptId int64 `json:"deptId" description:"部门ID"`
}
