// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// SysProvinces is the golang structure for table sys_provinces.
type SysProvinces struct {
	Id         int64       `json:"id"         description:"ID"`
	Title      string      `json:"title"      description:"栏目名"`
	Pid        int64       `json:"pid"        description:"父栏目"`
	ShortTitle string      `json:"shortTitle" description:"缩写"`
	Areacode   int         `json:"areacode"   description:"区域编码"`
	Zipcode    int         `json:"zipcode"    description:"邮政编码"`
	Pinyin     string      `json:"pinyin"     description:"拼音"`
	Lng        string      `json:"lng"        description:"经度"`
	Lat        string      `json:"lat"        description:"纬度"`
	Level      int         `json:"level"      description:"级别"`
	Tree       string      `json:"tree"       description:""`
	Sort       int         `json:"sort"       description:"排序"`
	Status     int         `json:"status"     description:"状态"`
	CreatedAt  *gtime.Time `json:"createdAt"  description:"创建时间"`
	UpdatedAt  *gtime.Time `json:"updatedAt"  description:"更新时间"`
}
