// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// SysAttachment is the golang structure for table sys_attachment.
type SysAttachment struct {
	Id        int64       `json:"id"        description:""`
	AppId     string      `json:"appId"     description:"应用ID"`
	MemberId  int64       `json:"memberId"  description:"用户"`
	CateId    uint64      `json:"cateId"    description:"分类"`
	Drive     string      `json:"drive"     description:"驱动"`
	Name      string      `json:"name"      description:"文件原始名"`
	Kind      string      `json:"kind"      description:"上传类型"`
	MetaType  string      `json:"metaType"  description:"类别"`
	NaiveType string      `json:"naiveType" description:"NaiveUI类型"`
	Path      string      `json:"path"      description:"本地路径"`
	FileUrl   string      `json:"fileUrl"   description:"url"`
	Size      int64       `json:"size"      description:"长度"`
	Ext       string      `json:"ext"       description:"扩展名"`
	Md5       string      `json:"md5"       description:"md5校验码"`
	Status    int         `json:"status"    description:"状态"`
	CreatedAt *gtime.Time `json:"createdAt" description:"创建时间"`
	UpdatedAt *gtime.Time `json:"updatedAt" description:"修改时间"`
}
