// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package service

import (
	"context"
	"hotgo/api/backend/role"
	"hotgo/internal/model/input/adminin"
)

type IAdminRole interface {
	Verify(ctx context.Context, path, method string) bool
	List(ctx context.Context, in adminin.RoleListInp) (list []*adminin.RoleListModel, totalCount int, err error)
	GetName(ctx context.Context, RoleId int64) (name string, err error)
	GetMemberList(ctx context.Context, RoleId int64) (list []*adminin.RoleListModel, err error)
	GetPermissions(ctx context.Context, reqInfo *role.GetPermissionsReq) (MenuIds []int64, err error)
	UpdatePermissions(ctx context.Context, reqInfo *role.UpdatePermissionsReq) error
	Edit(ctx context.Context, in *role.EditReq) (err error)
	Delete(ctx context.Context, in *role.DeleteReq) (err error)
}

var localAdminRole IAdminRole

func AdminRole() IAdminRole {
	if localAdminRole == nil {
		panic("implement not found for interface IAdminRole, forgot register?")
	}
	return localAdminRole
}

func RegisterAdminRole(i IAdminRole) {
	localAdminRole = i
}
