// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package service

import (
	"context"
	"hotgo/api/backend/menu"
	"hotgo/api/backend/role"
	"hotgo/internal/model/input/adminin"
)

type IAdminMenu interface {
	RoleList(ctx context.Context, in adminin.MenuRoleListInp) (*adminin.MenuRoleListModel, error)
	SearchList(ctx context.Context, req *menu.SearchListReq) (*menu.SearchListRes, error)
	MaxSort(ctx context.Context, req *menu.MaxSortReq) (*menu.MaxSortRes, error)
	NameUnique(ctx context.Context, req *menu.NameUniqueReq) (*menu.NameUniqueRes, error)
	CodeUnique(ctx context.Context, req *menu.CodeUniqueReq) (*menu.CodeUniqueRes, error)
	Delete(ctx context.Context, req *menu.DeleteReq) error
	Edit(ctx context.Context, req *menu.EditReq) (err error)
	View(ctx context.Context, req *menu.ViewReq) (res *menu.ViewRes, err error)
	List(ctx context.Context, req *menu.ListReq) (lists []map[string]interface{}, err error)
	GetMenuList(ctx context.Context, memberId int64) (lists role.DynamicRes, err error)
}

var localAdminMenu IAdminMenu

func AdminMenu() IAdminMenu {
	if localAdminMenu == nil {
		panic("implement not found for interface IAdminMenu, forgot register?")
	}
	return localAdminMenu
}

func RegisterAdminMenu(i IAdminMenu) {
	localAdminMenu = i
}
