// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package service

import (
	"context"
)

type IAdminMemberPost interface {
	UpdatePostIds(ctx context.Context, member_id int64, post_ids []int64) (err error)
	GetMemberByIds(ctx context.Context, member_id int64) (post_ids []int64, err error)
}

var localAdminMemberPost IAdminMemberPost

func AdminMemberPost() IAdminMemberPost {
	if localAdminMemberPost == nil {
		panic("implement not found for interface IAdminMemberPost, forgot register?")
	}
	return localAdminMemberPost
}

func RegisterAdminMemberPost(i IAdminMemberPost) {
	localAdminMemberPost = i
}
