// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package service

import (
	"context"
	"hotgo/internal/model/input/adminin"
)

type IAdminDept interface {
	NameUnique(ctx context.Context, in adminin.DeptNameUniqueInp) (*adminin.DeptNameUniqueModel, error)
	Delete(ctx context.Context, in adminin.DeptDeleteInp) error
	Edit(ctx context.Context, in adminin.DeptEditInp) (err error)
	Status(ctx context.Context, in adminin.DeptStatusInp) (err error)
	MaxSort(ctx context.Context, in adminin.DeptMaxSortInp) (*adminin.DeptMaxSortModel, error)
	View(ctx context.Context, in adminin.DeptViewInp) (res *adminin.DeptViewModel, err error)
	List(ctx context.Context, in adminin.DeptListInp) (list adminin.DeptListModel, err error)
	ListTree(ctx context.Context, in adminin.DeptListTreeInp) (list []*adminin.DeptListTreeModel, err error)
	GetName(ctx context.Context, id int64) (name string, err error)
}

var localAdminDept IAdminDept

func AdminDept() IAdminDept {
	if localAdminDept == nil {
		panic("implement not found for interface IAdminDept, forgot register?")
	}
	return localAdminDept
}

func RegisterAdminDept(i IAdminDept) {
	localAdminDept = i
}
