// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package service

import (
	"context"
	"hotgo/internal/model/input/adminin"
)

type IAdminNotice interface {
	Delete(ctx context.Context, in adminin.NoticeDeleteInp) error
	Edit(ctx context.Context, in adminin.NoticeEditInp) (err error)
	Status(ctx context.Context, in adminin.NoticeStatusInp) (err error)
	MaxSort(ctx context.Context, in adminin.NoticeMaxSortInp) (*adminin.NoticeMaxSortModel, error)
	View(ctx context.Context, in adminin.NoticeViewInp) (res *adminin.NoticeViewModel, err error)
	List(ctx context.Context, in adminin.NoticeListInp) (list []*adminin.NoticeListModel, totalCount int, err error)
}

var localAdminNotice IAdminNotice

func AdminNotice() IAdminNotice {
	if localAdminNotice == nil {
		panic("implement not found for interface IAdminNotice, forgot register?")
	}
	return localAdminNotice
}

func RegisterAdminNotice(i IAdminNotice) {
	localAdminNotice = i
}
