// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package service

import (
	"context"
	"hotgo/internal/model/input/adminin"
)

type IAdminPost interface {
	Delete(ctx context.Context, in adminin.PostDeleteInp) error
	Edit(ctx context.Context, in adminin.PostEditInp) (err error)
	MaxSort(ctx context.Context, in adminin.PostMaxSortInp) (*adminin.PostMaxSortModel, error)
	NameUnique(ctx context.Context, in adminin.PostNameUniqueInp) (*adminin.PostNameUniqueModel, error)
	CodeUnique(ctx context.Context, in adminin.PostCodeUniqueInp) (*adminin.PostCodeUniqueModel, error)
	View(ctx context.Context, in adminin.PostViewInp) (res *adminin.PostViewModel, err error)
	List(ctx context.Context, in adminin.PostListInp) (list []*adminin.PostListModel, totalCount int, err error)
	GetMemberByStartName(ctx context.Context, memberId int64) (name string, err error)
	Status(ctx context.Context, in adminin.PostStatusInp) (err error)
}

var localAdminPost IAdminPost

func AdminPost() IAdminPost {
	if localAdminPost == nil {
		panic("implement not found for interface IAdminPost, forgot register?")
	}
	return localAdminPost
}

func RegisterAdminPost(i IAdminPost) {
	localAdminPost = i
}
