// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package service

import (
	"context"
	"hotgo/api/backend/member"
	"hotgo/internal/model/input/adminin"
)

type IAdminMember interface {
	UpdateProfile(ctx context.Context, in adminin.MemberUpdateProfileInp) (err error)
	UpdatePwd(ctx context.Context, in adminin.MemberUpdatePwdInp) (err error)
	ResetPwd(ctx context.Context, in adminin.MemberResetPwdInp) (err error)
	EmailUnique(ctx context.Context, in adminin.MemberEmailUniqueInp) (*adminin.MemberEmailUniqueModel, error)
	MobileUnique(ctx context.Context, in adminin.MemberMobileUniqueInp) (*adminin.MemberMobileUniqueModel, error)
	NameUnique(ctx context.Context, in adminin.MemberNameUniqueInp) (*adminin.MemberNameUniqueModel, error)
	VerifySuperId(ctx context.Context, verifyId int64) bool
	Delete(ctx context.Context, in adminin.MemberDeleteInp) error
	Edit(ctx context.Context, in adminin.MemberEditInp) (err error)
	MaxSort(ctx context.Context, in adminin.MemberMaxSortInp) (*adminin.MemberMaxSortModel, error)
	View(ctx context.Context, in adminin.MemberViewInp) (res *adminin.MemberViewModel, err error)
	List(ctx context.Context, in adminin.MemberListInp) (list []*adminin.MemberListModel, totalCount int, err error)
	LoginMemberInfo(ctx context.Context, req *member.InfoReq) (res *adminin.MemberLoginModel, err error)
	Login(ctx context.Context, in adminin.MemberLoginInp) (res *adminin.MemberLoginModel, err error)
	RoleMemberList(ctx context.Context, in adminin.RoleMemberListInp) (list []*adminin.MemberListModel, totalCount int, err error)
	Status(ctx context.Context, in adminin.MemberStatusInp) (err error)
	GetIdByCode(ctx context.Context, in adminin.GetIdByCodeInp) (res *adminin.GetIdByCodeModel, err error)
}

var localAdminMember IAdminMember

func AdminMember() IAdminMember {
	if localAdminMember == nil {
		panic("implement not found for interface IAdminMember, forgot register?")
	}
	return localAdminMember
}

func RegisterAdminMember(i IAdminMember) {
	localAdminMember = i
}
