// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package service

import (
	"context"
	"hotgo/internal/model/input/sysin"

	"github.com/gogf/gf/v2/frame/g"
)

type ISysDictType interface {
	Tree(ctx context.Context) (list []g.Map, err error)
	Delete(ctx context.Context, in sysin.DictTypeDeleteInp) error
	Edit(ctx context.Context, in sysin.DictTypeEditInp) (err error)
	Select(ctx context.Context, in sysin.DictTypeSelectInp) (list sysin.DictTypeSelectModel, err error)
}

var localSysDictType ISysDictType

func SysDictType() ISysDictType {
	if localSysDictType == nil {
		panic("implement not found for interface ISysDictType, forgot register?")
	}
	return localSysDictType
}

func RegisterSysDictType(i ISysDictType) {
	localSysDictType = i
}
