// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package service

import (
	"context"
	"hotgo/internal/model"
	"hotgo/internal/model/entity"
	"hotgo/internal/model/input/sysin"
)

type ISysConfig interface {
	GetSmtp(ctx context.Context) (conf *model.EmailConfig, err error)
	GetConfigByGroup(ctx context.Context, in sysin.GetConfigInp) (*sysin.GetConfigModel, error)
	ConversionType(ctx context.Context, models *entity.SysConfig) (value interface{}, err error)
	UpdateConfigByGroup(ctx context.Context, in sysin.UpdateConfigInp) error
}

var localSysConfig ISysConfig

func SysConfig() ISysConfig {
	if localSysConfig == nil {
		panic("implement not found for interface ISysConfig, forgot register?")
	}
	return localSysConfig
}

func RegisterSysConfig(i ISysConfig) {
	localSysConfig = i
}
