// ================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// You can delete these comments if you wish manually maintain this interface file.
// ================================================================================

package service

import (
	"context"
	"hotgo/api/servmsg"
	"hotgo/internal/library/network/tcp"
)

type (
	IAuthClient interface {
		Instance() *tcp.Client
		Start(ctx context.Context)
		Stop(ctx context.Context)
		OnResponseAuthSummary(ctx context.Context, req *servmsg.AuthSummaryRes)
		OnResponseExampleHello(ctx context.Context, req *servmsg.ExampleHelloRes)
	}
	ICronClient interface {
		Instance() *tcp.Client
		Start(ctx context.Context)
		Stop(ctx context.Context)
		OnCronDelete(ctx context.Context, req *servmsg.CronDeleteReq) (res *servmsg.CronDeleteRes, err error)
		OnCronEdit(ctx context.Context, req *servmsg.CronEditReq) (res *servmsg.CronEditRes, err error)
		OnCronStatus(ctx context.Context, req *servmsg.CronStatusReq) (res *servmsg.CronStatusRes, err error)
		OnCronOnlineExec(ctx context.Context, req *servmsg.CronOnlineExecReq) (res *servmsg.CronOnlineExecRes, err error)
		DefaultInterceptor(ctx context.Context, msg *tcp.Message) (err error)
	}
)

var (
	localAuthClient IAuthClient
	localCronClient ICronClient
)

func CronClient() ICronClient {
	if localCronClient == nil {
		panic("implement not found for interface ICronClient, forgot register?")
	}
	return localCronClient
}

func RegisterCronClient(i ICronClient) {
	localCronClient = i
}

func AuthClient() IAuthClient {
	if localAuthClient == nil {
		panic("implement not found for interface IAuthClient, forgot register?")
	}
	return localAuthClient
}

func RegisterAuthClient(i IAuthClient) {
	localAuthClient = i
}
