// ================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// You can delete these comments if you wish manually maintain this interface file.
// ================================================================================

package service

import (
	"context"
	"hotgo/internal/model/input/msgin"
)

type (
	ITCPServer interface {
		OnAuthSummary(ctx context.Context, args ...interface{})
		CronDelete(ctx context.Context, in *msgin.CronDelete) (err error)
		CronEdit(ctx context.Context, in *msgin.CronEdit) (err error)
		CronStatus(ctx context.Context, in *msgin.CronStatus) (err error)
		CronOnlineExec(ctx context.Context, in *msgin.CronOnlineExec) (err error)
		Start(ctx context.Context)
		Stop(ctx context.Context)
	}
)

var (
	localTCPServer ITCPServer
)

func TCPServer() ITCPServer {
	if localTCPServer == nil {
		panic("implement not found for interface ITCPServer, forgot register?")
	}
	return localTCPServer
}

func RegisterTCPServer(i ITCPServer) {
	localTCPServer = i
}
